#!/bin/bash
echo "Create volumes for sonarqube for persist the data"
docker volume create --name sonarqube_data
docker volume create --name sonarqube_logs
docker volume create --name sonarqube_extensions

echo "running the sonarqube container "
docker run -itd --name sonarqube \
-p 9000:9000 \
-e SONAR_JDBC_USERNAME=admin \
-e SONAR_JDBC_PASSWORD=admin \
-v sonarqube_data:/opt/sonarqube/data \
-v sonarqube_extensions:/opt/sonarqube/extensions \
-v sonarqube_logs:/opt/sonarqube/logs \
sonarqube

echo "Login=admin .Password=admin"
